baseURL = 'https://codingclinician.netlify.app/'
languageCode = 'en-us'
title = 'Home'
theme = ["hugo-admonitions", "PaperMod"]


[params]
  showShareButtons = false
  showPostNavLinks = true
  showReadingTime = false
  showToc = true
  ShowRssButtonInSectionTermList= true
  showPostThumbnails = false
  showBreadCrumbs = false
  defaultTheme = "light"
  mainSections = ["books","movies","music"]
   hideFooter = true
   


[params.assets]
favicon = "/icons/favicon.ico"
favicon16x16 = "/icons/favicon-16x16.png"
favicon32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"

  [params.profileMode]
  enabled= false
 Title = "Hi, this is Nischal."
 subtitle = "Exploring book, movies and music."
   imageUrl= "images/Nischal.jpeg" # optional
    imageTitle= "title of image as alt" # optional
   imageWidth = "150px"
   imageHeight = "auto"
   
  [params.homeInfoParams]
Title = "👋 Hi, I'm Nischal."
Content = "When I’m not buried in textbooks, I’m lost in music, films, and fiction. This space is where I explore the art that stays with me — sometimes loud, sometimes subtle, always meaningful."
imageUrl= "images/Nischal.jpeg" # optional
    imageTitle= "Nischal" # optional
   imageWidth = "200px"
   imageHeight = "auto"
   


 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "https://gmail.com/jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"




[[menu.main]]
  name = "📚 Books"
  url = "/books/"
  weight = 10

[[menu.main]]
  name = "🎬 Movies"
  url = "/movies/"
  weight = 11

[[menu.main]]
  name = "🎵 Music"
  url = "/music/"
  weight = 12
