baseURL = 'https://nischaldawadi.com.np/'
languageCode = 'en-us'
title = 'Nischal Dawadi'
theme = ["hugo-admonitions", "PaperMod"]
pagination.pagerSize = 4

[params]
  showShareButtons = false
  showPostNavLinks = true
  showReadingTime = false
  showToc = true
  ShowRssButtonInSectionTermList= true
  showPostThumbnails = false
  showBreadCrumbs = false
  defaultTheme = "light"
  mainSections = ["books","movies","music","posts"]
   hideFooter = true
  enableRobotsTXT = true
  env = "production"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

   
   [sitemap]
  changefreq = 'weekly'
  priority = 0.8
   

[params.label]
text = "Digital Home"
[params.assets]
favicon = "/icons/favicon.ico"
favicon16x16 = "/icons/favicon-16x16.png"
favicon32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"

  [params.profileMode]
  enabled= false
 Title = "Hi, this is Nischal."
 subtitle = "Exploring book, movies and music."
   imageUrl= "images/Nischal.webp" # optional
    imageTitle= "title of image as alt" # optional
   imageWidth = "150px"
   imageHeight = "auto"

  [params.homeInfoParams]
Title = "👋 Hi, I'm <span class='highlight-name'>Nischal</span>"
Content = "Between the quiet moments of life, I’m lost in music, films, and fiction. This space is where I explore the art that stays with me — sometimes loud, sometimes subtle, always meaningful."
imageUrl= "images/Nischal.webp" # optional
    imageTitle= "Nischal" # optional
   imageWidth = "200px"
   imageHeight = "190px"
   


 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "https://gmail.com/jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"


[[menu.main]]
  name = "📚 Books"
  url = "/posts/books/"
  weight = 10

[[menu.main]]
  name = "🎬 Movies"
  url = "/posts/movies/"
  weight = 11

[[menu.main]]
  name = "🎵 Music"
  url = "/posts/music/"
  weight = 12
  
  [[menu.main]]
  name = " Exam"
  url = "/Exam-related/"
  weight = 14
  

