baseURL = 'https://codingclinician.netlify.app/'
languageCode = 'en-us'
title = 'Nischal Home'
theme = 'PaperMod'


[params]
  ShowShareButtons = true
  ShowToc = false
  showPostNavLinks = true
  showReadingTime = true
  showToc = true
  showPostThumbnails = true
  showBreadCrumbs = true
  defaultTheme = "auto"
  mainSections = ["books", "movies","music"]
  
  [params.homeInfoParams]
 Title = "Welcome to Digital Home"
 Content = "Exploring books, movies and music."
   imageUrl= "images/home-cover.jpg" # optional
    imageTitle= "title of image as alt" # optional
    imageWidth= 200 # custom size
    imageHeight= 200 # custom size
  
 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "https://gmail.com/jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"

[menu]
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 1

  [[menu.main]]
    identifier = "movies"
    name = "Movies"
    url = "/movies/"
    weight = 2

 [[menu.main]]
  identifier= "music"
 name = "Music"
 url = "/music/"
 description = "Journey through Music"
weight = 3
