baseURL = 'https://codingclinician.netlify.app/'
languageCode = 'en-us'
title = 'Nischal Home'
theme = ["hugo-admonitions", "PaperMod"]


[params]
  showShareButtons = false
  showPostNavLinks = true
  showReadingTime = false
  showToc = true
  ShowRssButtonInSectionTermList= true
  showPostThumbnails = false
  showBreadCrumbs = false
  defaultTheme = "light"
  mainSections = ["books", "movies","music"]
   hideFooter = true
   
[params.label]
text = "Nischal Home"
icon = "images/profile.jpg"
iconHeight = "60"


  [params.profileMode]
  enabled= false
 Title = "Hello this is Nischal."
 subtitle = "Exploring book, movies and music."
   imageUrl= "images/Nischal.jpeg" # optional
    imageTitle= "title of image as alt" # optional
   imageWidth = "150px"
   imageHeight = "auto"
   
  [params.homeInfoParams]
Title = "Hello this is Nischal"
Content = "Exploring book, movies and music"
imageUrl= "images/Nischal.jpeg" # optional
    imageTitle= "Nischal" # optional
   imageWidth = "auto"
   imageHeight = "auto"
   


 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "https://gmail.com/jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"

[menu]
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 1

  [[menu.main]]
    identifier = "movies"
    name = "Movies"
    url = "/movies/"
    weight = 2

 [[menu.main]]
  identifier= "music"
 name = "Music"
 url = "/music/"
 description = "Journey through Music"
weight = 3

