baseURL = 'https://codingclinician.netlify.app/'
languageCode = 'en-us'
title = 'Nischal Home'
theme = 'PaperMod'


[params]
  ShowShareButtons = false
  ShowToc = false
  showPostNavLinks = true
  showReadingTime = false
  showToc = true
  showPostThumbnails = true
  showBreadCrumbs = true
  defaultTheme = "light"
  mainSections = ["books", "movies","music"]
   hideFooter = true
    
  [params.profileMode]
  enabled= true
 Title = "Hello this is Nischal."
 subtitle = "Exploring books, movies and music."
   imageUrl= "images/profile.jpg" # optional
    imageTitle= "title of image as alt" # optional

   
  
 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "https://gmail.com/jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"

[menu]
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 1

  [[menu.main]]
    identifier = "movies"
    name = "Movies"
    url = "/movies/"
    weight = 2

 [[menu.main]]
  identifier= "music"
 name = "Music"
 url = "/music/"
 description = "Journey through Music"
weight = 3
