baseURL = 'https://codingclinician.netlify.app/'
languageCode = 'en-us'
title = 'Nischal Home'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = false
  defaultTheme = "auto"
  mainSections = ["books", "movies"]
  
[params.profileMode]
enabled = true
title = "Welcome to Digital Home"
subtitle="Exploring books and movies." 

    imageUrl= "images/home-cover.jpg" # optional
    imageWidth= 300 # custom size
    imageHeight= 300 # custom size
  
 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "https://gmail.com/jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"

[menu]
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 1

  [[menu.main]]
    identifier = "movies"
    name = "Movies"
    url = "/movies/"
    weight = 2
